export const GIVE_CONSENT_SUCCESS = 'GIVE_CONSENT_SUCCESS';
export const GIVE_CONSENT_FAILURE = 'GIVE_CONSENT_FAILURE';

export const GET_ALL_CONSENTS_SUCCESS = 'GET_ALL_CONSENTS_SUCCESS';
export const GET_ALL_CONSENTS_FAILURE = 'GET_ALL_CONSENTS_FAILURE';